services:
  # Commenté pour utiliser MySQL à la place
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: belote
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belote
      MYSQL_USER: belote
      MYSQL_PASSWORD: belote
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # Utiliser l'émulation pour exécuter l'image amd64 sur arm64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - mysql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: belote
      DB_PORT: 3306
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    command: >-
      sh -c "npm install && npm run dev"

  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: unless-stopped

  # Commenté pour utiliser phpMyAdmin à la place
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@belote.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  # db-data:
  # pgadmin-data:
  mysql-data:
